### ISSUE TITLE
Hey Dekrypt! I have a question

### ISSUE THREAD

**Issue by PwnOriginal** [dekrypted/dekrypted#2]
i made a site and it uses the html code for krypt.fun, just asking if u are ok with me using it. Well Cya!

**Comment by dekrypted** [comment]
cant stop you :) of course man!

**Comment by PwnOriginal** [comment]
> cant stop you :) of course man!

Appriciate it! Thanks. if u wanna check it out its https://cake.wtf

**Comment by PwnOriginal** [comment]
> cant stop you :) of course man!

btw, last question. can u send the files of ur website without all the sensitive ones so i can cross check?

**Comment by dekrypted** [comment]
you got them all

**Comment by PwnOriginal** [comment]
> you got them all

👍 alr sweet! CYA
